import type { Titular } from "./types"

export const titularesEjemplo: Titular[] = [
  {
    tipoDocumento: "DNI",
    documento: "12345678",
    nombre: "Juan",
    apellido: "Pérez",
    fechaNacimiento: new Date("1990-05-15"),
    direccion: "Av. Corrientes 1234, Buenos Aires",
    grupoSanguineo: "A",
    factorRH: "+",
    donanteOrganos: true,
    licencias: [
      {
        id: "1",
        tipo: "B",
        observaciones: "Licencia para automóviles",
        fechaCreacion: new Date("2020-03-15"),
      },
      {
        id: "2",
        tipo: "A",
        observaciones: "Licencia para motocicletas",
        fechaCreacion: new Date("2019-08-22"),
      },
    ],
  },
  {
    tipoDocumento: "DNI",
    documento: "87654321",
    nombre: "María",
    apellido: "González",
    fechaNacimiento: new Date("1985-08-22"),
    direccion: "Calle Falsa 123, Córdoba",
    grupoSanguineo: "O",
    factorRH: "-",
    donanteOrganos: false,
    licencias: [
      {
        id: "3",
        tipo: "B",
        observaciones: "Licencia para automóviles",
        fechaCreacion: new Date("2021-01-10"),
      },
    ],
  },
  {
    tipoDocumento: "DNI",
    documento: "11223344",
    nombre: "Carlos",
    apellido: "Pérez",
    fechaNacimiento: new Date("1978-12-03"),
    direccion: "Av. San Martín 567, Rosario",
    grupoSanguineo: "B",
    factorRH: "+",
    donanteOrganos: true,
    licencias: [],
  },
  {
    tipoDocumento: "Pasaporte",
    documento: "AB123456",
    nombre: "Ana",
    apellido: "Martínez",
    fechaNacimiento: new Date("1992-03-18"),
    direccion: "Belgrano 890, Mendoza",
    grupoSanguineo: "AB",
    factorRH: "+",
    donanteOrganos: true,
    licencias: [
      {
        id: "4",
        tipo: "C",
        observaciones: "Licencia para camiones",
        fechaCreacion: new Date("2022-06-15"),
      },
    ],
  },
  {
    tipoDocumento: "DNI",
    documento: "55667788",
    nombre: "Juan",
    apellido: "Rodríguez",
    fechaNacimiento: new Date("1988-07-25"),
    direccion: "Mitre 456, La Plata",
    grupoSanguineo: "A",
    factorRH: "-",
    donanteOrganos: false,
    licencias: [
      {
        id: "5",
        tipo: "A",
        observaciones: "Licencia para motocicletas",
        fechaCreacion: new Date("2023-02-20"),
      },
      {
        id: "6",
        tipo: "B",
        observaciones: "Licencia para automóviles",
        fechaCreacion: new Date("2023-03-10"),
      },
    ],
  },
]
